apiVersion: 1
datasources:
  - name: lokxy
    type: loki
    uid: lokxy
    access: proxy
    orgId: 1
    url: http://lokxy:3100
    editable: false
    isDefault: true
    jsonData:
      timeInterval: 30s
  - name: loki1
    type: loki
    uid: loki1
    access: proxy
    orgId: 1
    url: http://loki1:3101
    editable: false
    jsonData:
      timeInterval: 30s
  - name: loki2
    type: loki
    uid: loki2
    access: proxy
    orgId: 1
    url: http://loki2:3102
    editable: false
    jsonData:
      timeInterval: 30s
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      streamingEnabled:
        search: true
